[project]
name = "rotating_proxies"

[build-system]
requires = [
  "setuptools >= 45",
  "wheel",
  "setuptools_scm[toml]>=6.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "rotating_proxies/version.py"
local_scheme = "dirty-tag"
