[project]
name = "scrapy-rotating-proxies"

[build-system]
requires = [
  "attrs > 16.0.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "rotating_proxies/version.py"
local_scheme = "dirty-tag"
